// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

// TODO: This sample tool downloads Azure Key Vault Managed certificates
// they can be self-signed certs or certs generated by CAs integrated
// with AKV. The format can be be PKCS12 or PEM.

package subcommands

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/lease"
	"github.com/Azure/go-autorest/autorest/to"
	"github.com/paulomarquesc/azbloblease/azbloblease/internal/common"
	"github.com/paulomarquesc/azbloblease/azbloblease/internal/config"
	"github.com/paulomarquesc/azbloblease/azbloblease/internal/models"
	"github.com/paulomarquesc/azbloblease/azbloblease/internal/utils"
)

// RenewLease - attempts to renew an Azure blob storage lease
func RenewLease(cntx context.Context, subscriptionID, resourceGroupName, accountName, container, blobName, leaseID, environment, cloudConfigFile string, iterations, waittimesec int, cred azcore.TokenCredential) models.ResponseInfo {

	response := models.ResponseInfo{
		SubscriptionID:     &subscriptionID,
		ResourceGroupName:  &resourceGroupName,
		StorageAccountName: &accountName,
		ContainerName:      &container,
		BlobName:           &blobName,
		Status:             to.StringPtr(config.Fail()),
	}

	// Getting storage client and keys
	storageAccountClient, err := common.GetStorageClient(subscriptionID, environment, cloudConfigFile, cred)
	if err != nil {
		utils.ConsoleOutput(fmt.Sprintf("an error ocurred while getting storage account client: %v.", err), config.Stderr())
		response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
		return response
	}

	accountKeys, err := common.GetStorageAccountKey(cntx, storageAccountClient, resourceGroupName, accountName)
	if err != nil {
		utils.ConsoleOutput(fmt.Sprintf("an error ocurred while getting storage account keys: %v.", err), config.Stderr())
		response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
		return response
	}

	// // Create a credential object; this is used to access account while using azblob module.
	// credential, err := azblob.NewSharedKeyCredential(accountName, *accountKeys.Keys[0].Value)
	// if err != nil {
	// 	utils.ConsoleOutput(fmt.Sprintf("an error ocurred while obtaining azblob credential: %v.", err), config.Stderr())
	// 	response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
	// 	return response
	// }

	// // Getting blob endpoint
	// blobEndppointURL, err := url.Parse(
	// 	common.GetAccountBlobEndpoint(cntx, &storageAccountClient, resourceGroupName, accountName),
	// )

	// if err != nil {
	// 	utils.ConsoleOutput(fmt.Sprintf("an error ocurred while obtaining blob endpoint: %v.", err), config.Stderr())
	// 	response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
	// 	return response
	// }

	// // Getting specific blob client
	// blobURL := fmt.Sprintf("%v%v/%v", blobEndppointURL.String(), container, blobName)

	// blobClient, err := blockblob.NewClientWithSharedKeyCredential(blobURL, credential, nil)
	// if err != nil {
	// 	utils.ConsoleOutput(fmt.Sprintf("an error occurred trying to create blob client for blob %v, error: %v", blobURL, err), config.Stderr())
	// 	response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
	// 	return response
	// }

	// Getting blob client
	azBlobClient, err := common.GetBlobClient(cntx, "", accountName, resourceGroupName, *accountKeys.Keys[0].Value, storageAccountClient, cred)
	if err != nil {
		utils.ConsoleOutput(fmt.Sprintf("an error ocurred while obtaining az blob client: %v", err), config.Stderr())
		response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
		return response
	}

	blobRelativePath := fmt.Sprintf("%v/%v", container, blobName)
	blobURL := fmt.Sprintf("%v%v", azBlobClient.URL, blobRelativePath)

	blockBlobClient, err := blockblob.NewClientWithSharedKeyCredential(blobURL, &azBlobClient.SharedKeyCredential, nil)
	if err != nil {
		utils.ConsoleOutput(fmt.Sprintf("an error occurred trying to create blob client for blob %v, error: %v", blobURL, err), config.Stderr())
		response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
		return response
	}

	_, err = blockBlobClient.GetProperties(cntx, nil)
	if err != nil {
		utils.ConsoleOutput(fmt.Sprintf("an error occurred trying to get blob %v, error: %v", blobURL, err), config.Stderr())
		response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
		return response
	}

	// Renew Lease
	for i := 0; i < iterations; i++ {

		// Getting lease client
		blobLeaseClient, err := lease.NewBlobClient(blockBlobClient, &lease.BlobClientOptions{
			LeaseID: &leaseID,
		})

		if err != nil {
			utils.ConsoleOutput(fmt.Sprintf("an error ocurred while acquiring lease client: %v", err), config.Stderr())
			response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
		} else {

			// Renew lease
			leaseResponse, err := blobLeaseClient.RenewLease(
				cntx,
				&lease.BlobRenewOptions{},
			)

			if err != nil {
				utils.ConsoleOutput(fmt.Sprintf("an error ocurred while renewing lease: %v.", err), config.Stderr())
				response.ErrorMessage = to.StringPtr(strings.Replace(err.Error(), "\"", "", -1))
				return response
			}

			renewedLeaseID := *leaseResponse.LeaseID
			diagnosticMessage := fmt.Sprintf("Renewed lease %v, iteration %v, request id %v", renewedLeaseID, i, *leaseResponse.RequestID)
			utils.ConsoleOutput(diagnosticMessage, config.Stderr())
		}

		time.Sleep(time.Duration(waittimesec) * time.Second)
	}

	response.Status = to.StringPtr(config.SuccessOnRenew())
	return response
}
